server:
  port: ${SANJY_SERVER_PORT}

sanjy-server:
  logging:
    level: ${SANJY_SERVER_LOGGING_LEVEL}
    file-path: ${SANJY_SERVER_LOGGING_FILE_PATH:}
    appender: ${SANJY_SERVER_LOGGING_APPENDER}
  application:
    name: ${spring.application.name}
    version: "@project.version@"
    description: "@project.description@"
    contact:
      name: ToDo-put-name #ToDo: Put real name
      url: https://google.com #ToDo: Put real site
      email: admin@admin.com #ToDo: Put real email
    documentation:
      url: https://google.com #ToDo: Put real site
      description: ToDo-put-documentation-description #ToDo: Put real doc

spring:
  application:
    name: sanJy-server

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # SQL Logging
#        show_sql: true
#        format_sql: true
#        highlight_sql: true
  ai:
    mcp:
      server:
        name: ${spring.application.name}-mcp-server
        version: "@project.version@"
        type: SYNC
        instructions: "This server provides diet and meal management tools. You can create and retrieve diet plans with nutritional targets, register meal consumption records (both standard and free meals), view today's meals, search historical meal data with pagination, and analyze diet adherence statistics over time periods."
        sse-message-endpoint: ${SANJY_SERVER_MCP_SSE_MESSAGE_ENDPOINT}
        sse-endpoint: ${SANJY_SERVER_MCP_SSE_ENDPOINT}
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

  datasource:
    url: ${SANJY_SERVER_DATABASE_JDBC_URL}
    username: ${SANJY_SERVER_DATABASE_USERNAME}
    password: ${SANJY_SERVER_DATABASE_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  main:
    banner-mode: off

  threads:
    virtual:
      enabled: true

  aot:
    enabled: true

springdoc:
  api-docs:
    path: ${SANJY_SERVER_OPEN_API_API_DOCS_PATH}
    resolve-schema-properties: true
    enabled: ${SANJY_SERVER_OPEN_API_API_DOCS_ENABLE}
  override-with-generic-response: false
  swagger-ui:
    path: ${SANJY_SERVER_OPEN_API_SWAGGER_UI_REDIRECT_PATH}
    enabled: ${SANJY_SERVER_OPEN_API_SWAGGER_UI_ENABLE}

logging:
  level:
    org:
      hibernate:
        # Log SQL
#        orm.jdbc.bind: TRACE
