server:
  port: ${SANJY_SERVER_PORT}

sanjy-server:
  logging:
    level: ${SANJY_SERVER_LOGGING_LEVEL}
    file-path: ${SANJY_SERVER_LOGGING_FILE_PATH:}
    appender: ${SANJY_SERVER_LOGGING_APPENDER}

spring:
  application:
    name: sanJy-server

  jpa:
    properties:
      hibernate:
        # SQL Logging
#        show_sql: true
#        format_sql: true
#        highlight_sql: true
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

  datasource:
    url: jdbc:postgresql://localhost:5432/diet_control
    username: admin_usr
    password: admin_pass

  main:
    banner-mode: off

  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  override-with-generic-response: false
  paths-to-exclude: /**/api-docs,/swagger-ui/**,/**/swagger-resources/**
  swagger-ui:
    path: /

logging:
  level:
    org:
      hibernate:
        # Log SQL
#        orm.jdbc.bind: TRACE
